---
title: "stringr"
author: "dududu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning=FALSE,
  error=TRUE,
  message=FALSE
)
```
```{r}
library(stringr)
```
1. 字符串的长度(空格也算)
```{r}
str_length(c("a","R for data science",NA))
str_pad(c("a", "ab", "abc"), 3) # 填充长度到3
str_trunc("R for data science", 10) # 截断长度为10
str_trim(c("a","b  ","a b")) # 移除空格
```
2. 字符串合并
```{r}
str_c("x",1:5, sep = "")
paste("x", 1:5, sep = "")

str_c("x", 1:5, collapse = "")
str_c("x", 1:5, collapse = "_")

str_c("x", str_c(sprintf("%03d", 1:5)))
```
3. 将部分字符重复
```{r}
str_dup(c("a","b"), c(3,2))
```
4. 字符串拆分
```{r}
str_split(c("10,8,7"),",")
str_split_fixed(c("10,8,7"  ),",", n = 2)
```
5. 字符串格式化输出
```{r}
str_glue("Pi = {pi}")
name <- c("李明","花花")
tel <- c("11223344556","11332255446")
str_glue("姓名：{name}", "电话：{tel}", .sep = "; ")
```
```{r}
df <- mtcars[1:3, ]
str_glue_data(df, "{rownames(df)} 总功率为{hp} KW.h")
```
6. 字符串排序
```{r}
x <- c("banana","apple","pear")
str_sort(x)
str_sort(c("香蕉","苹果","梨"),locale = "ch")

str_order(x)
```
7. 检测匹配
```{r}
# 检测是否存在匹配
str_detect(x, pattern = "p", negate = F) # negate：是否反向匹配
# 查找符合匹配条件的索引
str_which(x, pattern = "p")
# 计算匹配的次数
str_count(x,"p")
# 定位匹配的位置
str_locate(x,"a.")

# 是否以“a”开头或结尾
str_starts(x,"a")
str_ends(x, "a")
```
8. 提取字符串
```{r}
# 默认为str_sub(x, start = 1, end = -1)
str_sub(x,1,3)
str_sub(x,1,5)
str_sub(x,-3,-1)

# 提取符合条件的字符串
str_subset(x, "p", negate = F)
```
9. 提取匹配的内容
```{r}
x <- c("1987-2000", "2011-2020-2099")
str_extract(x, "\\d{4}")
str_match(x, "\\d{4}")
```
10. 修改字符串
```{r}
str_replace(x, "-", "/")
str_replace_all(x, "-", "/")
# stringr中用于查找、替换、匹配的函数都有一个后缀为“_all”的版本
```
11. 大小写转化
```{r}
str_to_lower("I love r language")
str_to_upper("I love r language")
str_to_title("I love r language")
```


